import { useEffect, useState } from "react";
import { CopyToClipboard } from "react-copy-to-clipboard";
import {
  CopyOutlined,
  DownloadOutlined,
  InfoCircleOutlined,
} from "@ant-design/icons";
import history from "../../history";
import moment from "dayjs";
import _ from "lodash";
import {
  Button,
  Modal,
  Select,
  App,
  Alert,
  Radio,
  Row,
  Col,
  Divider,
  Checkbox,
  Typography,
  Tag,
  Tooltip,
} from "antd";
import { NavLink } from "react-router-dom";
import axios from "axios";
import config from "../../config";
import PageContent from "../../components/PageContent";
import ErrorMsg from "../../components/ErrorMsg";
import withContext from "../../components/hoc/withContext";

import NameAutocomplete from "../project/Assembly/NameAutocomplete";
import qs from "query-string";
const { Text } = Typography;

const DatasetDownload = ({ rank, dataFormat, addError, user, dataset, location }) => {
  const { message } = App.useApp();
  const [error, setError] = useState(null);
  const [selectedDataFormat, setSelectedDataFormat] = useState("ColDP");
  const [exportUrl, setExportUrl] = useState(null);
  const [downloadModalVisible, setDownloadModalVisible] = useState(false);
  const [rootTaxon, setRootTaxon] = useState(null);
  const [synonyms, setSynonyms] = useState(false);
  const [bareNames, setBareNames] = useState(false);
  const [extinct, setExtinct] = useState(null);
  const [classification, setClassification] = useState(false);
  const [extended, setExtended] = useState(false);
  const [dataAccess, setDataAccess] = useState(null);
  const [minRank, setMinRank] = useState("GENUS");
  const [excludeRanksBelow, setExcludeRanksBelow] = useState(null);

  useEffect(() => {
    if (dataset) {
      getSettings();
    }
    const taxonID = _.get(qs.parse(_.get(location, "search")), "taxonID");
    if (taxonID && dataset) {
      getRootTaxon(taxonID);
    }
  }, []);

  useEffect(() => {
    if (dataset?.key) {
      getSettings();
      const taxonID = _.get(
        qs.parse(_.get(location, "search")),
        "taxonID"
      );
      if (taxonID) {
        getRootTaxon(taxonID);
      }
    }
  }, [dataset?.key]);

  const getSettings = () => {
    const key = dataset?.key;
    axios(`${config.dataApi}dataset/${key}/settings`)
      .then((res) => {
        setDataAccess(_.get(res, 'data["data access"]'));
      })
      .catch((err) => {
        console.log(err);
      });
  };

  const exportDataset = (options) => {
    axios
      .post(`${config.dataApi}dataset/${dataset?.key}/export`, options)
      .then((res) => {
        const uuid = res.data;
        setError(null);
        setExportUrl(`${config.dataApi}export/${uuid}`);
        history.push({
          pathname: `/download/${uuid}`,
        });
      })
      .catch((err) => addError(err));
  };

  const createCitation = () => {
    const authors = _.get(dataset, "authors", [])
      .map((a) => a.name)
      .join(", ");
    return `${dataset?.title}. ${authors} ${moment(dataset?.modified).format(
      "LL"
    )}`;
  };

  const getRootTaxon = (key) => {
    axios
      .get(
        `${config.dataApi}dataset/${dataset?.key}/taxon/${encodeURIComponent(
          key
        )}`
      )
      .then(({ data: rootTaxon }) => {
        setRootTaxon(rootTaxon);
      })
      .catch((err) => addError(err));
  };

  return (
    <PageContent>
      {error && (
        <Alert description={<ErrorMsg error={error} />} type="error" />
      )}
      {dataset?.origin === "external" && (
        <>
          <h3>Existing archives generated by the source</h3>
          <ul>
            <li>
              <a
                href={`${config.dataApi}dataset/${dataset?.key}/archive.zip`}
                target="_blank"
              >
                original archive
              </a>{" "}
              that was last imported into ChecklistBank.
            </li>
            <li>
              <NavLink
                to={{
                  pathname: `/dataset/${dataset?.key}/imports`,
                  search: "?showHistory=true",
                }}
                end
              >
                historic archives
              </NavLink>{" "}
              that were previously imported into ChecklistBank.
            </li>
            {dataAccess && (
              <li>
                <a href={dataAccess} target="_blank">
                  external archive
                </a>{" "}
                which is being served by the source right now.
              </li>
            )}
          </ul>
          <Divider></Divider>
        </>
      )}

      <h3>Generate new download</h3>
      <Row style={{ marginBottom: "10px", marginTop: "20px" }}>
        Archive format{" "}
        <a
          href="/about/formats#data-formats"
          target="_blank"
          style={{ marginLeft: "8px" }}
        >
          <InfoCircleOutlined />
        </a>
      </Row>
      <Row style={{ marginBottom: "10px", marginLeft: "20px" }}>
        <Radio.Group
          options={dataFormat
            .filter((f) => !["proxy", "acef"].includes(f.name?.toLowerCase()))
            .map((f) => ({
              label: (
                <Tooltip title={f?.title}>
                  <span>{f.name}</span>
                </Tooltip>
              ),
              value: f.name,
            }))}
          value={selectedDataFormat}
          onChange={(e) => setSelectedDataFormat(e.target.value)}
          optionType="button"
        />
      </Row>

      <Row style={{ marginBottom: "10px", marginTop: "20px" }}>
        Content{" "}
        <a
          href="/about/formats#data-content"
          target="_blank"
          style={{ marginLeft: "8px" }}
        >
          <InfoCircleOutlined />
        </a>
      </Row>
      <Row style={{ marginBottom: "10px", marginLeft: "20px" }}>
        <Checkbox
          checked={classification}
          onChange={(e) => setClassification(e.target.checked)}
          style={{ marginLeft: "8px" }}
        >
          Classification
        </Checkbox>

        {dataFormat.find(
          (f) =>
            f.name.toLowerCase() === selectedDataFormat?.toLowerCase() &&
            !!f.extendedContent
        ) && (
          <Checkbox
            checked={extended}
            onChange={(e) => setExtended(e.target.checked)}
            style={{ marginLeft: "8px" }}
          >
            Extended
          </Checkbox>
        )}
      </Row>

      <Row style={{ marginBottom: "10px", marginTop: "20px" }}>
        Filter by higher taxon:&nbsp;
        {rootTaxon && (
          <>
            <Tag
              closable
              onClose={() => {
                history.push({
                  pathname: location.pathname,
                });
                setRootTaxon(null);
              }}
            >
              <span
                dangerouslySetInnerHTML={{ __html: rootTaxon.labelHtml }}
              />
            </Tag>
          </>
        )}
        {!rootTaxon && "no"}
      </Row>
      <Row style={{ marginBottom: "10px", marginLeft: "20px" }}>
        <Col span={10}>
          <NameAutocomplete
            minRank={minRank}
            datasetKey={dataset?.key}
            defaultTaxonKey={
              _.get(qs.parse(_.get(location, "search")), "taxonID") || null
            }
            onError={(error) => setError(error)}
            onSelectName={(name) => {
              history.push({
                pathname: location.pathname,
                search: `?taxonID=${_.get(name, "key")}`,
              });
              getRootTaxon(name.key);
            }}
            onResetSearch={() => {
              history.push({
                pathname: location.pathname,
              });
              setRootTaxon(null);
            }}
          />
          <Text>Minimum rank for search: </Text>
          <Radio.Group
            onChange={(e) => setMinRank(e.target.value)}
            value={minRank}
          >
            <Radio value={"FAMILY"}>Family</Radio>
            <Radio value={"GENUS"}>Genus</Radio>
            <Radio value={"SPECIES"}>Species</Radio>
          </Radio.Group>
        </Col>
      </Row>

      <Row style={{ marginBottom: "10px", marginTop: "20px" }}>
        Exclude ranks below
      </Row>
      <Row style={{ marginBottom: "10px", marginLeft: "20px" }}>
        <Col>
          <Select
            style={{ width: 200 }}
            showSearch
            allowClear
            onChange={(val) => setExcludeRanksBelow(val)}
            options={rank.map((r) => ({ value: r, label: r }))}
          />
        </Col>
      </Row>

      <Row style={{ marginBottom: "10px", marginTop: "20px" }}>
        Exclude synonyms:&nbsp;
        <Checkbox
          checked={synonyms}
          onChange={(e) => setSynonyms(e.target.checked)}
        ></Checkbox>
      </Row>

      <Row style={{ marginBottom: "10px", marginTop: "20px" }}>
        Extinct only:&nbsp;
        <Checkbox
          checked={extinct}
          onChange={(e) => setExtinct(e.target.checked)}
        ></Checkbox>
      </Row>

      <Row style={{ marginBottom: "10px", marginTop: "20px" }}>
        {user && (
          <Button
            type="primary"
            onClick={() => {
              let options = {
                format: selectedDataFormat,
                synonyms: !synonyms,
                bareNames,
                extended,
                extinct,
                classification,
              };
              if (classification) {
                options.taxGroups = true;
              }
              if (rootTaxon) {
                options.root = {};
                options.root.id = rootTaxon.id;
              }
              if (excludeRanksBelow) {
                options.minRank = excludeRanksBelow;
              }
              exportDataset(options);
            }}
          >
            Download <DownloadOutlined />
          </Button>
        )}
        {!user && `<b>Please login to create downloads!</b>`}
      </Row>

      <Row style={{ marginTop: "24px" }}>
        <Col span={24}>
          <Divider plain>Please cite as:</Divider>
          <CopyToClipboard
            text={`${rootTaxon ? rootTaxon.label + " in " : ""}${
              dataset?.citation || createCitation()
            }`}
            onCopy={() => message.info(`Copied citation to clipboard`)}
          >
            <p style={{ textAlign: "center", cursor: "pointer" }}>
              {rootTaxon && (
                <span
                  dangerouslySetInnerHTML={{
                    __html: rootTaxon.labelHtml + " in ",
                  }}
                />
              )}
              {dataset?.citation ? (
                <span
                  dangerouslySetInnerHTML={{
                    __html: dataset?.citation,
                  }}
                />
              ) : (
                createCitation()
              )}
            </p>
          </CopyToClipboard>
        </Col>
      </Row>
      <Modal
        title="Your download will be available at this link"
        open={downloadModalVisible}
        onCancel={() => setDownloadModalVisible(false)}
        footer={null}
      >
        <a href={exportUrl}>{exportUrl}</a>{" "}
        <CopyToClipboard
          text={exportUrl}
          onCopy={() => message.info(`Copied "${exportUrl}" to clipboard`)}
        >
          <Button>
            <CopyOutlined />
          </Button>
        </CopyToClipboard>
      </Modal>
    </PageContent>
  );
};

const mapContextToProps = ({ rank, dataFormat, addError, user }) => ({
  rank,
  user,
  dataFormat,
  addError,
});
export default withContext(mapContextToProps)(DatasetDownload);
