import { useEffect, useState } from "react";
import { CopyToClipboard } from "react-copy-to-clipboard";
import {
  CopyOutlined,
  DownloadOutlined,
  InfoCircleOutlined,
} from "@ant-design/icons";
import history from "../../history";
import { formatTime } from "../../dateTime";
import _ from "lodash";
import {
  Button,
  Modal,
  Select,
  App,
  Alert,
  Radio,
  Row,
  Col,
  Divider,
  Checkbox,
  Typography,
  Tag,
  Tooltip,
  Spin,
} from "antd";
import { NavLink } from "react-router-dom";
import axios from "axios";
import config from "../../config";
import PageContent from "../../components/PageContent";
import ErrorMsg from "../../components/ErrorMsg";
import withContext from "../../components/hoc/withContext";

import NameAutocomplete from "../project/Assembly/NameAutocomplete";
import qs from "query-string";
const { Text } = Typography;

/**
 * `datasetKey` is the dataset in the URL and is the ONLY thing every request
 * here may be keyed on. `dataset` comes from AppContext, which holds the simple
 * record and can momentarily describe a different dataset entirely - deriving
 * the export key from it is what once submitted a Lepidoptera export of COL
 * against iBOL. Use it for display, never to build a URL.
 */
const DatasetDownload = ({ rank, dataFormat, addError, user, datasetKey, dataset, location }) => {
  const { message } = App.useApp();
  const [error, setError] = useState(null);
  const [selectedDataFormat, setSelectedDataFormat] = useState("ColDP");
  const [exportUrl, setExportUrl] = useState(null);
  const [downloadModalVisible, setDownloadModalVisible] = useState(false);
  const [rootTaxon, setRootTaxon] = useState(null);
  const [synonyms, setSynonyms] = useState(false);
  const [bareNames, setBareNames] = useState(false);
  const [extinct, setExtinct] = useState(null);
  const [classification, setClassification] = useState(false);
  const [extended, setExtended] = useState(false);
  const [dataAccess, setDataAccess] = useState(null);
  const [minRank, setMinRank] = useState("GENUS");
  const [excludeRanksBelow, setExcludeRanksBelow] = useState(null);
  // The citation needs `citation` / `authors` / `modified`, which are not on the
  // simple record in context, so this page fetches the full one just for that.
  // Nothing else waits on it - the Download button is usable immediately.
  const [fullDataset, setFullDataset] = useState(null);
  const [citationLoading, setCitationLoading] = useState(false);

  useEffect(() => {
    if (!datasetKey) return;
    getSettings();
    getCitationData();
    const taxonID = _.get(qs.parse(_.get(location, "search")), "taxonID");
    if (taxonID) {
      getRootTaxon(taxonID);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [datasetKey]);

  const getSettings = () => {
    axios(`${config.dataApi}dataset/${datasetKey}/settings`)
      .then((res) => {
        setDataAccess(_.get(res, 'data["data access"]'));
      })
      .catch((err) => {
        console.log(err);
      });
  };

  const getCitationData = () => {
    setCitationLoading(true);
    axios(`${config.dataApi}dataset/${datasetKey}`)
      .then((res) => {
        setFullDataset(res.data);
        setCitationLoading(false);
      })
      .catch(() => {
        setFullDataset(null);
        setCitationLoading(false);
      });
  };

  const exportDataset = (options) => {
    if (!datasetKey) return;
    axios
      .post(`${config.dataApi}dataset/${datasetKey}/export`, options)
      .then((res) => {
        // the endpoint answers with a JobInfo, like every other job submission
        const uuid = res.data?.key;
        setError(null);
        setExportUrl(`${config.dataApi}export/${uuid}`);
        history.push({
          pathname: `/download/${uuid}`,
        });
      })
      .catch((err) => addError(err));
  };

  // Built from the full record, which carries authors/modified; falls back to
  // the context dataset's title so there is something sensible to show if the
  // full fetch failed.
  const createCitation = () => {
    const src = fullDataset || dataset;
    const authors = _.get(src, "authors", [])
      .map((a) => a.name)
      .join(", ");
    const modified = src?.modified ? ` ${formatTime(src.modified, "LL")}` : "";
    return `${src?.title}. ${authors}${modified}`;
  };

  const getRootTaxon = (key) => {
    axios
      .get(
        `${config.dataApi}dataset/${datasetKey}/taxon/${encodeURIComponent(
          key
        )}`
      )
      .then(({ data: rootTaxon }) => {
        setRootTaxon(rootTaxon);
      })
      .catch((err) => addError(err));
  };

  return (
    <PageContent>
      {error && (
        <Alert description={<ErrorMsg error={error} />} type="error" />
      )}
      {dataset?.origin === "external" && (
        <>
          <h3>Existing archives generated by the source</h3>
          <ul>
            <li>
              <a
                href={`${config.dataApi}dataset/${datasetKey}/archive.zip`}
                target="_blank"
              >
                original archive
              </a>{" "}
              that was last imported into ChecklistBank.
            </li>
            <li>
              <NavLink
                to={{
                  pathname: `/dataset/${datasetKey}/imports`,
                  search: "?showHistory=true",
                }}
                end
              >
                historic archives
              </NavLink>{" "}
              that were previously imported into ChecklistBank.
            </li>
            {dataAccess && (
              <li>
                <a href={dataAccess} target="_blank">
                  external archive
                </a>{" "}
                which is being served by the source right now.
              </li>
            )}
          </ul>
          <Divider></Divider>
        </>
      )}

      <h3>Generate new download</h3>
      <Row style={{ marginBottom: "10px", marginTop: "20px" }}>
        Archive format{" "}
        <a
          href="/about/formats#data-formats"
          target="_blank"
          style={{ marginLeft: "8px" }}
        >
          <InfoCircleOutlined />
        </a>
      </Row>
      <Row style={{ marginBottom: "10px", marginLeft: "20px" }}>
        <Radio.Group
          options={dataFormat
            .filter((f) => !["proxy", "acef"].includes(f.name?.toLowerCase()))
            .map((f) => ({
              label: (
                <Tooltip title={f?.title}>
                  <span>{f.name}</span>
                </Tooltip>
              ),
              value: f.name,
            }))}
          value={selectedDataFormat}
          onChange={(e) => setSelectedDataFormat(e.target.value)}
          optionType="button"
        />
      </Row>

      <Row style={{ marginBottom: "10px", marginTop: "20px" }}>
        Content{" "}
        <a
          href="/about/formats#data-content"
          target="_blank"
          style={{ marginLeft: "8px" }}
        >
          <InfoCircleOutlined />
        </a>
      </Row>
      <Row style={{ marginBottom: "10px", marginLeft: "20px" }}>
        <Checkbox
          checked={classification}
          onChange={(e) => setClassification(e.target.checked)}
          style={{ marginLeft: "8px" }}
        >
          Classification
        </Checkbox>

        {dataFormat.find(
          (f) =>
            f.name.toLowerCase() === selectedDataFormat?.toLowerCase() &&
            !!f.extendedContent
        ) && (
          <Checkbox
            checked={extended}
            onChange={(e) => setExtended(e.target.checked)}
            style={{ marginLeft: "8px" }}
          >
            Extended
          </Checkbox>
        )}
      </Row>

      <Row style={{ marginBottom: "10px", marginTop: "20px" }}>
        Filter by higher taxon:&nbsp;
        {rootTaxon && (
          <>
            <Tag
              closable
              onClose={() => {
                history.push({
                  pathname: location.pathname,
                });
                setRootTaxon(null);
              }}
            >
              <span
                dangerouslySetInnerHTML={{ __html: rootTaxon.labelHtml }}
              />
            </Tag>
          </>
        )}
        {!rootTaxon && "no"}
      </Row>
      <Row style={{ marginBottom: "10px", marginLeft: "20px" }}>
        <Col span={10}>
          <NameAutocomplete
            minRank={minRank}
            datasetKey={datasetKey}
            defaultTaxonKey={
              _.get(qs.parse(_.get(location, "search")), "taxonID") || null
            }
            onError={(error) => setError(error)}
            onSelectName={(name) => {
              history.push({
                pathname: location.pathname,
                search: `?taxonID=${_.get(name, "key")}`,
              });
              getRootTaxon(name.key);
            }}
            onResetSearch={() => {
              history.push({
                pathname: location.pathname,
              });
              setRootTaxon(null);
            }}
          />
          <Text>Minimum rank for search: </Text>
          <Radio.Group
            onChange={(e) => setMinRank(e.target.value)}
            value={minRank}
          >
            <Radio value={"FAMILY"}>Family</Radio>
            <Radio value={"GENUS"}>Genus</Radio>
            <Radio value={"SPECIES"}>Species</Radio>
          </Radio.Group>
        </Col>
      </Row>

      <Row style={{ marginBottom: "10px", marginTop: "20px" }}>
        Exclude ranks below
      </Row>
      <Row style={{ marginBottom: "10px", marginLeft: "20px" }}>
        <Col>
          <Select
            style={{ width: 200 }}
            showSearch
            allowClear
            onChange={(val) => setExcludeRanksBelow(val)}
            options={rank.map((r) => ({ value: r, label: r }))}
          />
        </Col>
      </Row>

      <Row style={{ marginBottom: "10px", marginTop: "20px" }}>
        Exclude synonyms:&nbsp;
        <Checkbox
          checked={synonyms}
          onChange={(e) => setSynonyms(e.target.checked)}
        ></Checkbox>
      </Row>

      <Row style={{ marginBottom: "10px", marginTop: "20px" }}>
        Extinct only:&nbsp;
        <Checkbox
          checked={extinct}
          onChange={(e) => setExtinct(e.target.checked)}
        ></Checkbox>
      </Row>

      <Row style={{ marginBottom: "10px", marginTop: "20px" }}>
        {user && (
          <Button
            type="primary"
            onClick={() => {
              let options = {
                format: selectedDataFormat,
                synonyms: !synonyms,
                bareNames,
                extended,
                extinct,
                classification,
              };
              if (classification) {
                options.taxGroups = true;
              }
              if (rootTaxon) {
                options.root = {};
                options.root.id = rootTaxon.id;
              }
              if (excludeRanksBelow) {
                options.minRank = excludeRanksBelow;
              }
              exportDataset(options);
            }}
          >
            Download <DownloadOutlined />
          </Button>
        )}
        {!user && `<b>Please login to create downloads!</b>`}
      </Row>

      <Row style={{ marginTop: "24px" }}>
        <Col span={24}>
          <Divider plain>Please cite as:</Divider>
          {citationLoading ? (
            <p style={{ textAlign: "center" }}>
              <Spin size="small" />
            </p>
          ) : (
            <CopyToClipboard
              text={`${rootTaxon ? rootTaxon.label + " in " : ""}${
                fullDataset?.citation || createCitation()
              }`}
              onCopy={() => message.info(`Copied citation to clipboard`)}
            >
              <p style={{ textAlign: "center", cursor: "pointer" }}>
                {rootTaxon && (
                  <span
                    dangerouslySetInnerHTML={{
                      __html: rootTaxon.labelHtml + " in ",
                    }}
                  />
                )}
                {fullDataset?.citation ? (
                  <span
                    dangerouslySetInnerHTML={{
                      __html: fullDataset.citation,
                    }}
                  />
                ) : (
                  createCitation()
                )}
              </p>
            </CopyToClipboard>
          )}
        </Col>
      </Row>
      <Modal
        title="Your download will be available at this link"
        open={downloadModalVisible}
        onCancel={() => setDownloadModalVisible(false)}
        footer={null}
      >
        <a href={exportUrl}>{exportUrl}</a>{" "}
        <CopyToClipboard
          text={exportUrl}
          onCopy={() => message.info(`Copied "${exportUrl}" to clipboard`)}
        >
          <Button>
            <CopyOutlined />
          </Button>
        </CopyToClipboard>
      </Modal>
    </PageContent>
  );
};

const mapContextToProps = ({ rank, dataFormat, addError, user }) => ({
  rank,
  user,
  dataFormat,
  addError,
});
export default withContext(mapContextToProps)(DatasetDownload);
