---
name: Feature request
description: Suggest an idea for ChecklistBank
title: 'Feature: '
labels: enhancement
assignees: thomasstjerne
projects: ["CatalogueOfLife/2"]
body:
  - type: textarea
    attributes:
      label: Description
      description: explanation of the new feature
    validations:
      required: true
---

